#!/usr/bin/env python3
"""
AI Hallucination Detector in Code
Detects non-functional or impossible code that may have been generated by AI
"""

import ast
import importlib
import importlib.util
import sys
import os
import re
from pathlib import Path
from typing import List, Dict, Any, Set, Optional
from collections import defaultdict

class HallucinationDetector:
    """
    Detects hallucinations and non-functional code
    """
    
    def __init__(self, file_path: str):
        """
        Initializes the detector
        
        Args:
            file_path: Path to the file being analyzed
        """
        self.file_path = Path(file_path)
        self.file_content = self._read_file()
        self.ast_tree = self._parse_ast()
        self.hallucination_results: Dict[str, List[str]] = self.check_for_hallucinations() # Store detailed results
        self.known_modules = self._get_known_modules()
        self.defined_vars = set()
        self.used_vars = set()
        
    def _read_file(self) -> str:
        """
        Reads file, handling various encodings.
        
        Returns:
            str: File content
        """
        try:
            with open(self.file_path, 'r', encoding='utf-8', newline='') as f:
                return f.read()
        except (OSError, UnicodeDecodeError) as e:
            print(f"Error reading file {self.file_path}: {e}")
            return ""
    
    def _parse_ast(self) -> Optional[ast.AST]:
        """
        Parses file into AST.
        
        Returns:
            Optional[ast.AST]: AST tree or None on error
        """
        try:
            return ast.parse(self.file_content)
        except SyntaxError as e:
            print(f"Syntax error in file {self.file_path}: {e}")
            return None
        except Exception as e: # Catch other potential parsing errors
            print(f"Unknown parsing error in file {self.file_path}: {e}")
            return None
    
    def _get_known_modules(self) -> Set[str]:
        """
        Gets a list of known Python modules.
        
        Returns:
            Set[str]: Set of known modules.
        """
        known_modules = set()
        
        # Standard Python modules
        stdlib_modules = {
            'os', 'sys', 'json', 'datetime', 'pathlib', 'collections', 'itertools',
            'functools', 'operator', 'math', 'random', 'string', 're', 'hashlib',
            'hmac', 'base64', 'uuid', 'logging', 'unittest', 'doctest', 'pdb',
            'ast', 'inspect', 'types', 'copy', 'pickle', 'shelve', 'csv', 'configparser',
            'argparse', 'getopt', 'readline', 'subprocess', 'multiprocessing', 'threading',
            'queue', 'socket', 'email', 'urllib', 'http', 'ftplib', 'poplib', 'imaplib',
            'smtplib', 'telnetlib', 'socketserver', 'xml', 'html', 'webbrowser',
            'turtle', 'tkinter', 'random', 'statistics', 'decimal', 'fractions',
            'dataclasses', 'typing', 'concurrent', 'asyncio', 'contextvars'
        }
        
        # Adding standard modules
        known_modules.update(stdlib_modules)
        
        # Checking installed packages
        # try:
        #     import pkg_resources
        #     for dist in pkg_resources.working_set:
        #         known_modules.add(dist.project_name.lower())
        # except:
        #     pass
        
        # Checking modules in sys.modules
        known_modules.update(sys.modules.keys())
        
        return known_modules
    
    def verify_dependencies_exist(self) -> List[str]:
        """
        Checks the actual existence of imported modules.
        
        Returns:
            List[str]: List of non-existent modules.
        """
        issues = []
        
        if not self.ast_tree:
            return issues
        
        for node in ast.walk(self.ast_tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module_name = alias.name
                    line_num = getattr(node, 'lineno', 0)

                    if not self._module_exists(module_name):
                        issues.append(f"Non-existent module: {module_name} (line {line_num})")
                        continue

                    # For simple module imports - check importability
                    try:
                        importlib.import_module(module_name)
                    except ImportError:
                        issues.append(f"Cannot import module: {module_name} (line {line_num})")

            elif isinstance(node, ast.ImportFrom):
                module_name = node.module
                line_num = getattr(node, 'lineno', 0)

                if module_name and not self._module_exists(module_name):
                    issues.append(f"Non-existent module: {module_name} (line {line_num})")
                    continue

                if module_name:
                    try:
                        imported_module = importlib.import_module(module_name)
                        for alias in node.names:
                            # Handling asterisk import
                            if alias.name == '*':
                                continue

                            if not hasattr(imported_module, alias.name):
                                issues.append(f"Non-existent attribute {alias.name} in module {module_name} (line {line_num})")
                    except ImportError:
                        issues.append(f"Cannot import module: {module_name} (line {line_num})")
        
        return issues
    
    def _module_exists(self, module_name: str) -> bool:
        """
        Checks module existence.
        
        Args:
            module_name: Module name to check.
            
        Returns:
            bool: True if module exists.
        """
        try:
            spec = importlib.util.find_spec(module_name)
            return spec is not None
        except (ImportError, AttributeError):
            return False
    
    def check_unreachable_code(self) -> List[str]:
        """
        Finds unreachable code.
        
        Returns:
            List[str]: List of unreachable code.
        """
        issues = []
        
        if not self.ast_tree:
            return issues
        
        for node in ast.walk(self.ast_tree):
            if isinstance(node, ast.FunctionDef):
                # Checking code after return/raise/continue/break
                for i, stmt in enumerate(node.body):
                    if isinstance(stmt, (ast.Return, ast.Raise, ast.Break, ast.Continue)):
                        # Checking if there is code after this statement
                        if i < len(node.body) - 1:
                            issues.append(f"Unreachable code after {type(stmt).__name__} in function '{node.name}' (line {stmt.lineno})")
                
                # Checking for unreachability in if-else
                if isinstance(node.body[0], ast.If):
                    self._check_unreachable_in_if(node.body[0], issues, node.name)
        
        return issues
    
    def _check_unreachable_in_if(self, if_node: ast.If, issues: List[str], func_name: str):
        """
        Checks for unreachable code in if-constructs.
        
        Args:
            if_node: AST if node.
            issues: List to add issues.
            func_name: Function name for messages.
        """
        # Checking orelse branch
        if if_node.orelse and len(if_node.orelse) == 1:
            last_stmt = if_node.orelse[0]
            if isinstance(last_stmt, ast.If):
                # if-elif-else triangle
                return
            
        # Checking body branch
        if if_node.body and len(if_node.body) == 1:
            last_stmt = if_node.body[-1]
            if isinstance(last_stmt, (ast.Return, ast.Raise, ast.Break, ast.Continue)):
                # Entire if-else unreachable
                issues.append(f"Potentially unreachable else-block in function '{func_name}' (line {if_node.lineno})")
    
    def check_infinite_loops(self) -> List[str]:
        """
        Finds potential infinite loops.
        
        Returns:
            List[str]: List of potential infinite loops.
        """
        issues = []
        
        if not self.ast_tree:
            return issues
        
        for node in ast.walk(self.ast_tree):
            if isinstance(node, ast.While):
                # Checking while True condition
                if isinstance(node.test, ast.Constant) and node.test.value is True:
                    # Searching for break/return inside loop
                    has_escape = any(
                        isinstance(n, (ast.Break, ast.Return, ast.Raise))
                        for n in ast.walk(node)
                    )
                    if not has_escape:
                        issues.append(f"Potential infinite loop while True (line {node.lineno})")
            
            elif isinstance(node, ast.For):
                # Checking for empty range in for loop
                if isinstance(node.iter, ast.Constant):
                    iter_value = node.iter.value
                    if isinstance(iter_value, (list, tuple)) and len(iter_value) == 0:
                        # Empty range - loop will not execute
                        issues.append(f"Loop over empty range - will not execute (line {node.lineno})")
    
        return issues
    def check_missing_implementations(self) -> List[str]:
        """
        Checks for missing implementations.
        
        Returns:
            List[str]: List of incomplete implementations.
        """
        issues = []
        
        if not self.ast_tree:
            return issues
        
        for node in ast.walk(self.ast_tree):
            # Empty functions/classes
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if not node.body:
                    issues.append(f"Empty function '{node.name}' (line {node.lineno})")
                elif len(node.body) == 1 and isinstance(node.body[0], ast.Pass):
                    issues.append(f"Unimplemented function '{node.name}' (line {node.lineno})")
                elif len(node.body) == 1 and isinstance(node.body[0], ast.Expr) and isinstance(node.body[0].value, ast.Constant) and isinstance(node.body[0].value.value, str):
                    # Docstring only
                    issues.append(f"Function '{node.name}' contains only docstring (line {node.lineno})")

            elif isinstance(node, ast.ClassDef):
                if not node.body:
                    issues.append(f"Empty class '{node.name}' (line {node.lineno})")
                elif len(node.body) == 1 and isinstance(node.body[0], ast.Pass):
                    issues.append(f"Unimplemented class '{node.name}' (line {node.lineno})")

        # Searching for TODO/FIXME comments
        lines = self.file_content.split('\n')
        for i, line in enumerate(lines, 1):
            if re.search(r'\b(TODO|FIXME|HACK|XXX)\b', line, re.IGNORECASE):
                issues.append(f"Found {line.strip()} on line {i}")
        
        return issues
    
    def check_undefined_variables(self) -> List[str]:
        """
        Finds potentially undefined variables.

        Returns:
            List[str]: List of undefined variables.
        """
        issues = []

        if not self.ast_tree:
            return issues

        # Collecting defined variables
        self.defined_vars = set()
        self.used_vars = set()

        for node in ast.walk(self.ast_tree):
            # Variables from assignments
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        self.defined_vars.add(target.id)
            elif isinstance(node, ast.AnnAssign):
                if isinstance(node.target, ast.Name):
                    self.defined_vars.add(node.target.id)

            # Imported names
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    name = alias.asname if alias.asname else alias.name
                    self.defined_vars.add(name)
            elif isinstance(node, ast.ImportFrom):
                for alias in node.names:
                    name = alias.asname if alias.asname else alias.name
                    self.defined_vars.add(name)

            # Function parameters
            elif isinstance(node, ast.FunctionDef):
                for arg in node.args.args:
                    if isinstance(arg, ast.arg):
                        self.defined_vars.add(arg.arg)
                # Vararg and kwarg
                if node.args.vararg:
                    self.defined_vars.add(node.args.vararg.arg)
                if node.args.kwarg:
                    self.defined_vars.add(node.args.kwarg.arg)

            # Used variables
            elif isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                self.used_vars.add(node.id)

        # Checking for undefined variables
        undefined_vars = self.used_vars - self.defined_vars

        # Excluding built-in functions and exceptions
        excluded_vars = {
            'print', 'len', 'str', 'int', 'float', 'bool', 'list', 'dict', 'set', 'tuple',
            'range', 'enumerate', 'zip', 'map', 'filter', 'sum', 'max', 'min', 'abs',
            'round', 'sorted', 'reversed', 'any', 'all', 'next', 'iter',
            'Exception', 'ValueError', 'TypeError', 'IndexError', 'KeyError',
            'ImportError', 'AttributeError', 'OSError', 'IOError'
        }

        for var in undefined_vars:
            if not (var in dir(__builtins__) or var in excluded_vars or var.startswith('__')):
                issues.append(f"Potentially undefined variable: {var}")

        return issues
    
    def check_logical_inconsistencies(self) -> List[str]:
        """
        Проверка логических несоответствий
        
        Returns:
            List[str]: Список логических несоответствий
        """
        issues = []
        
        if not self.ast_tree:
            return issues
        
        for node in ast.walk(self.ast_tree):
            # Проверка на противоречивые условия
            if isinstance(node, ast.If):
                self._check_contradictory_conditions(node, issues)
        
        return issues
    
    def _check_contradictory_conditions(self, if_node: ast.If, issues: List[str]):
        line_num = if_node.lineno

        # Function to check for specific contradictory patterns in an expression
        def check_expression(expr: ast.expr):
            # Check for always true (e.g., x == x)
            if (isinstance(expr, ast.Compare) and 
                isinstance(expr.ops[0], ast.Eq) and 
                isinstance(expr.left, ast.Name) and
                len(expr.comparators) == 1 and
                isinstance(expr.comparators[0], ast.Name) and
                expr.left.id == expr.comparators[0].id):
                return 'always_true', expr.left.id
            
            # Check for always false (e.g., x != x)
            if (isinstance(expr, ast.Compare) and 
                isinstance(expr.ops[0], ast.NotEq) and 
                isinstance(expr.left, ast.Name) and
                len(expr.comparators) == 1 and
                isinstance(expr.comparators[0], ast.Name) and
                expr.left.id == expr.comparators[0].id):
                return 'always_false', expr.left.id
            return None, None

        # Traverse the test expression of the if statement
        true_cond_vars = set()
        false_cond_vars = set()

        for node in ast.walk(if_node.test): # Walk through the entire test expression
            result_type, var_id = check_expression(node)
            if result_type == 'always_true':
                true_cond_vars.add(var_id)
            elif result_type == 'always_false':
                false_cond_vars.add(var_id)
        
        # Check if both always-true and always-false conditions exist for the same variable
        if true_cond_vars.intersection(false_cond_vars):
            issues.append(f"Противоречивое условие (например, x==x и x!=x) в if (строка {line_num})")
    
    def check_for_hallucinations(self) -> Dict[str, List[str]]:
        """
        Запуск всех проверок на галлюцинации
        
        Returns:
            Dict[str, List[str]]: Результаты проверок по категориям
        """
        results = {
            'dependency_verification': [],
            'unreachable_code': [],
            'infinite_loops': [],
            'missing_implementations': [],
            'undefined_variables': [],
            'logical_inconsistencies': []
        }
        
        # Проверки
        results['dependency_verification'] = self.verify_dependencies_exist()
        results['unreachable_code'] = self.check_unreachable_code()
        results['infinite_loops'] = self.check_infinite_loops()
        results['missing_implementations'] = self.check_missing_implementations()
        results['undefined_variables'] = self.check_undefined_variables()
        results['logical_inconsistencies'] = self.check_logical_inconsistencies()
        
        # Подсчитываем общее количество проблем
        total_issues = sum(len(issues) for issues in results.values() if issues)
        
        
        self.hallucination_issues = [issue for issues in results.values() if issues for issue in issues]
        return results
    
    def generate_report(self) -> str:
        """
        Генерация детального отчета о галлюцинациях
        
        Returns:
            str: Отчет в текстовом формате
        """
        results = self.hallucination_results # Use stored results
        
        report = []
        report.append(f"=== Отчет о галлюцинациях AI: {self.file_path} ===\n")
        
        # Статистика анализа
        report.append("СТАТИСТИКА АНАЛИЗА:")
        report.append(f"  - Определено переменных: {len(self.defined_vars)}")
        report.append(f"  - Использовано переменных: {len(self.used_vars)}")
        report.append(f"  - Известных модулей: {len(self.known_modules)}")
        
        # Анализ по категориям
        for category, issues in results.items():
            category_name = category.replace('_', ' ').title()
            report.append(f"\n{category_name}:")
            
            if issues:
                for issue in issues:
                    report.append(f"  - {issue}")
            else:
                report.append("  Проблем не обнаружено")
        
        # Итоговая оценка
        total_issues = sum(len(issues) for issues in results.values() if issues)

        report.append(f"\n=== ИТОГОВАЯ ОЦЕНКА ===")
        if total_issues == 0:
            report.append("КОД ВЫГЛЯДИТ РЕАЛИСТИЧНО - галлюцинации не обнаружены")
        elif total_issues <= 3:
            report.append("КОД ТРЕБУЕТ ПРОВЕРКИ - обнаружены небольшие проблемы")
        else:
            report.append("КОД ПОДОЗРИТЕЛЕН - обнаружено много потенциальных галлюцинаций")
        
        return "\n".join(report)


def main():
    """Основная функция для запуска анализа"""
    if len(sys.argv) < 2:
        print("Использование: python hallucination_detector.py <путь_к_файлу>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    
    if not Path(file_path).exists():
        print(f"Ошибка: файл {file_path} не существует")
        sys.exit(1)
    
    detector = HallucinationDetector(file_path)
    report = detector.generate_report()
    print(report)
    
    # Возвращаем код выхода на основе результатов
    has_issues = any(len(issues) > 0 for issues in detector.hallucination_results.values() if issues)
    
    if has_issues:
        sys.exit(1)  # Обнаружены проблемы
    else:
        sys.exit(0)  # Проблем не обнаружено


if __name__ == "__main__":
    main()
